Update IOC conserver config generation

diff --git a/update-iocs-cf b/update-iocs-cf
--- a/update-iocs-cf
+++ b/update-iocs-cf
@@ -9,7 +9,7 @@ die() {
 
 [ -d /etc/conserver ] || exit 0
 
-tmp=$(tempfile) || die "Failed to create tempfile"
+tmp=$(mktemp) || die "Failed to create tempfile"
 
 echo "## Generated by update-iocs-cf" > "$tmp"
 
@@ -19,11 +19,7 @@ if mv -f "$tmp" "${IOCSCF:=/etc/conserver/iocs.cf}"
 then
     chmod a+r "${IOCSCF:=/etc/conserver/iocs.cf}"
     # poke daemon to reread config files
-    if type invoke-rc.d 2>&1 >/dev/null; then
-        invoke-rc.d conserver-server reload
-    else
-        /etc/init.d/conserver-server reload
-    fi
+    systemctl restart conserver.service
 else
     echo "Could not update /etc/conserver/iocs.cf"
 fi
